[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
Gtk4Makie = "478199e7-b407-4926-87ea-7196203a28d8"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
ShaderAbstractions = "65257c39-d410-5151-9873-9b3e5be5013e"
